[package]
name = "zsb-zotero-api"
description = "Zotero Local API client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zsb-core = { path = "../core" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
